//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public enum BiomeType
		{
			Ocean = 0,
			TropicalForest = 1,
			SeasonalForest = 2,
			Savana = 3,
			Desert = 4,
			TemperateRainForest = 5,
			TemperateForest = 6,
			Woodland = 7,
			GrassLand = 8,
			ShrubLand = 9,
			Tiaga = 10,
			Tundra = 11,
			Mountain = 12
		}
}

