//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public interface IBiomeGenerator
	{
		float GetHumidityAt(int x, int z);

		float GetTemperatureAt(int x, int z);
		
        float GetHeightAt(int x, int z);

        float GetSeaAt(int x, int z);

		//should we also care about base height?

		BiomeType GetBiomeAt(int x, int z);
		
		int GetHeightBiomeAt(int x, int z);
	}
}

