//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	/// <summary>
	/// First pass generator.
	/// Fills the data in a Chunk, first pass should include all terrain generation, caves, water, air etc 
	/// </summary>
	public interface IFirstPassGenerator
	{
		/// <summary>
		/// Generates the chunk. Nust not rely on any outside data, 
		/// shoudl all be based of noise calculations to prevent errors
		/// </summary>
		/// <param name="chunk">Chunk.</param>
		void generateChunk(Chunk chunk);
	}
}

