//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Random
	{
		private long seed = DateTime.Now.Millisecond; //TODO fix this!!

		public Random ()
		{
			
		}

		public Random (long seed)
		{
			this.seed = seed;
		}

		public int nextInt() {
			seed++;
			seed ^= (seed << 21);
			seed ^= (seed >> 35);
			seed ^= (seed << 4);
			return (int) seed;
		}

		public int nextInt(int max) {
			return (int) (max * nextDouble());
		}

		public long nextLong() {
			return (long) nextInt() << 32 ^ nextInt();
		}

		public double nextDouble() {
			return (nextLong() & 0x7FFFFFFFFFFFFFFFL) / (long.MaxValue + 1.0);
		}
	}
}

