//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class Block
	{
		public byte BlockId { get; set; }
		public Vector2 Texture {get; set; }
		public string Name { get; set; }

		public Block(byte id, string name, int texX, int texY)
		{
			BlockId = id;
			Texture = new Vector2 (texX, texY);
			Name = name;
		}
	}
}

