//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AssemblyCSharp
{

	public static class BlockManager
	{
        public static Block[] blockList = new Block[256];
        public static int[] blockOpacity = new int[256];

        public static readonly Block stone = new BlockStone(1, "stone", "stone");
        public static readonly Block dirt = new Block(2, "dirt", "dirt");
        public static readonly Block grass = new BlockGrass(3, "grass", "grass");
        public static readonly Block sand = new Block(4, "sand", "sand");
        public static readonly Block snow = new Block(5, "snow", "snow");
        public static readonly Block water = new Block(6, "water", "water");



		
        public static Block GetBlock(byte id) 
        {
            if (id == null)
                id = (byte)0;
            return blockList [id];
        }

        public static Block GetBlock(int id) 
        {
            if (id == null)
                id = (byte)0;
            return blockList [id];
        }

		public static Vector2 GetTexture(byte id)
		{
			return blockList [id].Texture;
		}

        public static int GetLightOpacity(byte id)
        {
            if (id == null)
                id = 0;
            return blockOpacity [id];
        }
	}
}

