//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	/*public enum BlockShape {
		Cube = 0,
		Slab = 1,
		CubeSlope = 3,
		SlabSlope = 4,
		CubeHalfSlope = 5,
		CubeOneSlope = 6,
		SlapOneSlope = 7,
		CubeOneHalfSlope = 8,
		CubeThreeSlope = 9,
		SlabThreeSlope = 10,
		CubeThreeHalfSlop = 11
	}

    public enum BlockPosition {
        Bottom = 0,
        Top = 1
    }

	public enum BlockRotation {
		North, //default
		East,
		South,
		West
	}*/

    public abstract class BlockGeo 
    {
        public int Id { get; private set; }
        private readonly string name;
        private ChunkRenderer cr;
        public float[] completeFace = {1, 1, 1, 1, 1, 1};

        public BlockGeo(int id, string name)
        {
            this.Id = id;
            this.name = name;

            if (BlockGeoManager.geoList [id] != null)
            {
                throw new Exception("Block Geo ID " + id.ToString() + " already exists for" + name);
            }
            BlockGeoManager.geoList [id] = this;
            BlockGeoManager.fillList [id] = this.GetFillValue();
        }

        public abstract float GetFillValue();


        public virtual void Render(Block block, ChunkRenderer cr, int x, int y, int posy, int z)
        {

        }

    }



}

