//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public enum BlockShape {
		Cube = 0,
		Slab = 1,
		CubeSlope = 3,
		SlabSlope = 4,
		CubeHalfSlope = 5,
		CubeOneSlope = 6,
		SlapOneSlope = 7,
		CubeOneHalfSlope = 8,
		CubeThreeSlope = 9,
		SlabThreeSlope = 10,
		CubeThreeHalfSlop = 11
	}

    public enum BlockPosition {
        Bottom = 0,
        Top = 1
    }

	public enum BlockRotation {
		North, //default
		East,
		South,
		West
	}
}

