//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AssemblyCSharp
{
	public class BlockManager
	{
		private Block[] blockList = new Block[] {
				
			new Block (1, 	"dirt",	0, 0),
			new Block (2, 	"grass",0, 1),
			new Block (3, 	"stone",0, 2),
			new Block (4, 	"sand", 0, 3),
			new Block (5, 	"snow", 1, 0),
			new Block (6, 	"snow", 1, 1),
			new Block (7, 	"snow", 1, 2),
			new Block (8, 	"snow", 1, 3),
			new Block (9,	"snow", 2, 0),
			new Block (10, 	"snow", 2, 1)
		};

		public Block GetBlock(byte id) 
		{
			return blockList [id];
		}

		public Vector2 GetTexture(byte id)
		{
			return blockList [id].Texture;
		}
	}
}

