//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public static class BlockGeoManager
    {

        public static BlockGeo[] geoList = new BlockGeo[16];
        public static float[] fillList = new float[16];
        
        public static BlockGeo cube = new GeoCube(0, "Cube");
        public static BlockGeo slab = new GeoSlab(1, "Slab");
        public static BlockGeo autoSlab = new GeoAutoSlopeSlab(2, "AutoSlab");


    }
}

