//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;


namespace AssemblyCSharp
{
    public static class TextureManager
    {

        private static readonly Dictionary<string, Vector2> textures = new Dictionary<string, Vector2>() {
            {"stone", new Vector2(0, 1)},
            {"dirt", new Vector2(0, 3)},
            {"grass", new Vector2(0, 2)},
            {"sand", new Vector2(2, 2)},
            {"water", new Vector2(0, 0)},
            {"snow", new Vector2(0, 0)},
            {"default", new Vector2(0, 0)}
        };

        public static Vector2 GetTexture(string name)
        {
            if (textures.ContainsKey(name))
            {
                return textures [name];
            } else
            {
                return textures ["default"];
            }
        }
    }
}

