//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public class BlockLightUpdate
    {
        public int posX { get; private set; }
        public int posY { get; private set; }
        public int posZ { get; private set; }
        public int level { get; private set; } 

        public BlockLightUpdate(int x, int y, int z, int level)
        {
            posX = x;
            posY = y;
            posZ = z;
            level = level;
        }
    }
}

