//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public class Chunk2
    {

        public int xPosition;
        public int zPosition;
        public int yHeight;
        int sectionSize = 16;

        public ChunkManager manager;

        //16*16 = 256

        Section2[] sections;
        public int firstSection; 

        byte[] biomeMap;

        public byte[] heightMap;
        public int maxHeight;
        public int minHeight;


        bool[] daylightColumnUpdates;


        public bool containsWater = false;

        public bool isDataLoaded = false;
        public bool isDaylightCalculated = false;
        public bool isLightCalculated = false;

        //section = 4096

        //all 65536
        public Chunk2(ChunkManager manager, int x, int z)
        {
            zPosition = x;
            zPosition = z;
            yHeight = 256;

            this.manager = manager;

            sections = new Section2[sectionSize];
            biomeMap = new byte[sectionSize * sectionSize];
            heightMap = new byte[sectionSize * sectionSize];
            daylightColumnUpdates = new bool[sectionSize * sectionSize];



        }


        public void SetData(byte[] chunkData)
        {
            int height = chunkData.Length / 256; //one slice of 16*16 data

            //split data into sections
            for (int x = 0; x < sectionSize; x++)
            {
                for (int z = 0; z < sectionSize; z++)
                {
                    for (int y = 0; y < height; y++)
                    {
                        //int xyz = x + 16 * (y + 256 * z);
                        byte block = chunkData[x + 16 * (y + 256 * z)];//TODO CHECK THIS

                        if (block != 0) {

                            int section = height / 16;
                            if (sections[section - 1] == null) {
                                sections[section - 1] = new Section2(section - 1);
                            }

                            sections[section - 1].SetBlockId(x + 16 * (y + 16 * z), block);
                        }
                    }
                }
            }

            SetFirstSection();
        }

        private void SetFirstSection()
        {
            for (int y = 15; y >= 0; y--)
            {
                if (this.sections[y] != null)
                {
                    this.firstSection = y;
                    return;
                }
            }
        }

        public Section2 GetSection(int y)
        {
            if (y > this.firstSection)
                return null;

            return this.sections [y];
        }

        /// <summary>
        /// A quickway to update a height, used during generation
        /// </summary>
        /// <param name="x">The x coordinate.</pforaram>
        /// <param name="z">The z coordinate.</param>
        /// <param name="height">Height.</param>
        public void SetHeightMap(int x, int z, byte height) 
        {
            this.heightMap[ x + 16 * z] = height;
        }

        public void SetBiomeMap(int x, int z, byte biome) 
        {
            this.biomeMap[ x + 16 * z] = biome;
        }

        public byte GetBlockId(int x, int y, int z)
        {
            int secY = y / 16;
            if (sections.Length < secY)
                return 0;

            Section2 sec = this.sections [secY];

            if (sec == null)
            {
                return 0;
            } else
            {
                int secYPos = y - (secY * 16); //TODO check this for speed issues
                return sec.GetBlockId(x, secYPos, z);
            }
        }


        public bool hasNeighbours(int x, int y, int z, int blockDist)
        {
            return manager.DoChunksExist(x, y, z, blockDist);
        }

        #region light operators

        public int GetLightOpacity(int x, int y, int z) 
        {
            return BlockManager.GetLightOpacity(GetBlockId(x, y, z));
        }

        public void GenerateDaylight() 
        {
            //bool secChanged[] = false;
            for (int x = 0; x < 16; x++)
            {
                for (int z = 0; z < 16; z++)
                {
                    for (int y = (this.firstSection * sectionSize) + sectionSize - 1; y > 0; y --)
                    {

                        int lightLevel = 15;

                        lightLevel -= this.GetLightOpacity(x, y, z);
                        if (lightLevel > 0) {
                            Section2 sec = this.sections[y /16];
                            sec.SetDatlightData(x, y % 16, z, lightLevel);
                        }

                    }

                    this.daylightColumnUpdates[x + 16 * z] = true;
                }
            }
        }

        public void SpreadDaylight()
        {

        }

        #endregion
    }
}

