//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public class ChunkCache
    {

        private Chunk2[,] chunkCache;


        /// <summary>
        /// 
        /// </summary>
        /// <param name="x">The global x coordinate.</param>
        /// <param name="z">The global z coordinate.</param>
        /// <param name="dist">Dist.</param>
        public ChunkCache(int x, int z, int dist)
        {

        }
    }
}

