//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class BlockManager
	{

		private Block _grass = new Block {
			BlockId = 1,
			Texture = Vector2(0,0)
		};

		public BlockManager ()
		{
		}

		public Block GetBlock(byte id) 
		{

		}


	}
}

