//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
    public class LightGenerator
    {
        public LightGenerator()
        {
        }

        public void GenerateDaylight(Chunk chunk) 
        {
            int sectionSize = chunk.sectionSize;

            int min = chunk.minHeight;
            int max = chunk.maxHeight;

            int maxSection = max / sectionSize;
            int minSection = min / sectionSize;

            int noSections = chunk.sections.Length;
            //quick fill to max + 1

            //are there empty sections above max?
            if (noSections < maxSection - 1)
            {
                //loop through each section and set daylight
                for (int i = noSections - 1; i > maxSection; i--)
                {
                    Section section = chunk.sections[i];

                    for (int x = 0; x < sectionSize; x++)
                    {
                        for (int z = 0; z < sectionSize; z++)
                        {
                            for (int y = 0; y < sectionSize; y++)
                            {
                                section.daylightData[x,y,z] = 15;
                            }   
                        }
                    }
                }
            }

            //now fillin the partialsections
            for (int i = maxSection; i >= minSection; i--)
            {
                Section section = chunk.sections[i];
                int globalY = i * sectionSize;

                for (int x = 0; x < sectionSize; x++)
                {
                    for (int z = 0; z < sectionSize; z++)
                    {
                        int height = chunk.heightMap[x, z];
                        for (int y = sectionSize - 1; y >= 0 && y + globalY > height ; y--)
                        {
                            section.daylightData[x,y,z] = 15;
                        }   
                    }
                }
            }
            
        }

        public void SpreadDaylight(Chunk chunk)
        {

        }

        public void SpreadDaylightFromSides(Chunk chunk)
        {

        }
    }
}

