//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	/// <summary>
	/// World config. A class for saving all user settings
	/// </summary>
	public class WorldConfig
	{
		private string defaultSeed = "PHILSWORLD";
		private WorldGeneratorList defaultGenerator = WorldGeneratorList.PERLIN;
		
		public string Seed {
			get;
			set;
		}
		
		public WorldGeneratorList Generator {
			get;
			set;
		}
		
		public WorldConfig ()
		{
			Seed = defaultSeed;
			Generator = defaultGenerator;
		}
		
		public WorldConfig (string seed)
		{
			Seed = seed;
			Generator = defaultGenerator;
		}
	}
	
	public enum WorldGeneratorList {
		PERLIN = 1,
		FLAT = 2
	} 
}

